language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t benjaminchua/docker-travis -f Dockerfile.dev .

script:
    - docker run -e CI=true benjaminchua/docker-travis npm run test